api:
  dashboard: false
  insecure: false

log:
  level: DEBUG
  filePath: "log-file.log"
  format: json

accessLog:
  filePath: "log-access.log"
  bufferingSize: 100

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  http:
    acme:
      email: ankoayfeno@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: http
