name: Curl URL Every 4 Minutes
on:
  schedule:
    - cron: "*/4 * * * *"

jobs:
  fetch_url:
    runs-on: ubuntu-latest
    steps:
      - name: Curl URL to active
        run: |
          curl -s https://ml-karama.onrender.com
          curl -s https://api-ml-karama.onrender.com
      
