name: deploy dev
run-name: pipeline declanched by ${{ github.actor }} on branch ${{ github.ref }}

on:
  push:
    branches:
      - develop

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if file exists
        run: ls -lah $(pwd)/docker-compose.yaml

      - name: Deploy to Dev server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc"
          SOURCE: "./docker-compose.yaml" # Vérifie bien ce chemin
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          TARGET: "/home/${{ vars.REMOTE_USER }}/traefik/ml_karama/"
          SCRIPT_AFTER: |
            docker-compose -f "/home/${{ vars.REMOTE_USER }}/traefik/ml_karama/docker-compose.yaml" --profile dev down
            docker-compose -f "/home/${{ vars.REMOTE_USER }}/traefik/ml_karama/docker-compose.yaml" --profile dev up -d
